### ISSUE TITLE
Feature: [Server restart in ...] instead of "shutdown"

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/mod-server-auto-shutdown#1]
**Describe your feature request or suggestion in detail**

Currently when someone uses the `.server restart` command, the system messages say "Server shutdown in ..."
Since it is supposed to be back up soon, the system message should state "Server restart in ..."

**Describe a possible solution to your Feature or Suggestion in detail**

Add a new system message for .server restart to clarify.

**Additional context**

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan can we change the message of the module from SHUTDOWN to RESTART ?

**Comment by Winfidonarleyan** [comment]
#2
